# fly.toml file generated for extreme-frontend on 2024-07-21T14:06:32+09:00

app = "extreme-frontend"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "hkg"
processes = []

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
